"""Figures and the markdown report."""
from pathlib import Path

import matplotlib
import pandas as pd

from covaudit import __version__
from covaudit.metrics import worst_group_gap

matplotlib.use("Agg")  # draw without a screen (containers, CI)
import matplotlib.pyplot as plt  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402

COLORS = {"FAIL": "#b03a3a", "LOW": "#8a8f98", "OK": "#2a7f8e", "ALL": "#1f3a5f"}


def _label(row):
    name = row["name"] if "name" in row and str(row["name"]) not in ("", "nan") else row["group"]
    return f"{name} (n={int(row['n'])})"


def plot_group_coverage(table, alpha, path, title=None):
    """Dot per group with its confidence interval; dashed line at 1 - alpha.

    Red = FAIL, grey = LOW, teal = OK, navy = ALL. Intervals running past the
    left edge (tiny groups) are clipped and marked with an arrow. Returns path.
    """
    rows = table[table["n"] > 0].reset_index(drop=True)
    target = 1 - alpha
    big = rows[rows["n"] >= 30]
    left = min((big["ci_low"].min() if len(big) else target) - 0.02, target - 0.05)
    left = max(0.0, left)

    fig, ax = plt.subplots(figsize=(7.5, 0.45 * len(rows) + 1.4))
    for i, row in rows.iterrows():
        y = len(rows) - 1 - i
        color = COLORS["ALL"] if row["group"] == "ALL" else COLORS.get(row["status"], "#555")
        lo = max(row["ci_low"], left)
        ax.plot([lo, row["ci_high"]], [y, y], color=color, lw=2)
        ax.plot(row["coverage"], y, "o", color=color, ms=6)
        if row["ci_low"] < left:
            ax.plot(left, y, "<", color=color, ms=6)
    ax.axvline(target, ls="--", color="black", lw=1)
    ax.set_yticks(range(len(rows)))
    ax.set_yticklabels([_label(r) for _, r in rows.iloc[::-1].iterrows()])
    ax.set_xlim(left, 1.005)
    ax.set_xlabel("coverage with 95% Clopper-Pearson interval")
    ax.set_title(title or f"Per-group coverage (target {target:.0%})")
    handles = [Line2D([0], [0], color=COLORS[s], marker="o", lw=2, label=s)
               for s in ("FAIL", "LOW", "OK")]
    ax.legend(handles=handles, loc="upper left", bbox_to_anchor=(1.01, 1),
              frameon=False, fontsize=9)
    fig.tight_layout()

    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def _md_table(table):
    """Small markdown table (avoids an extra dependency)."""
    cols = [c for c in ["group", "name", "n", "coverage", "ci_low", "ci_high",
                        "avg_set_size", "status"] if c in table.columns]
    lines = ["| " + " | ".join(cols) + " |", "|" + "---|" * len(cols)]
    for _, r in table.iterrows():
        cells = [f"{r[c]:.4f}" if isinstance(r[c], float) else str(r[c]) for c in cols]
        lines.append("| " + " | ".join(cells) + " |")
    return "\n".join(lines)


def write_report(results_dir, out_dir, alpha=0.1):
    """Find result CSVs under results_dir, draw figures, write report.md.

    Missing parts are skipped. Returns (report_path, notes).
    """
    results_dir, out_dir = Path(results_dir), Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    notes = []
    lines = ["# covaudit report", "",
             f"Generated by covaudit {__version__} from `{results_dir}` "
             f"(alpha = {alpha}).", "", "## Single-seed audits", ""]

    audits = sorted(p for p in results_dir.rglob("audit_*.csv")
                    if out_dir not in p.parents)
    if not audits:
        notes.append(f"skipped single-seed audits: no audit_*.csv under {results_dir}")
        lines += ["_None found._", ""]
    for csv in audits:
        table = pd.read_csv(csv)
        parts = csv.stem.split("_")
        title = (f"{parts[1]} CP by {'_'.join(parts[2:])}" if len(parts) >= 3
                 else csv.stem)
        name = csv.stem if csv.parent == results_dir else f"{csv.parent.name}_{csv.stem}"
        png = plot_group_coverage(table, alpha, out_dir / f"{name}.png", title=title)
        lines += [f"### {title} (`{csv.relative_to(results_dir)}`)", "",
                  f"![{title}]({png.name})", "", _md_table(table), "",
                  f"Worst-group gap: {worst_group_gap(table, alpha):.4f}", ""]

    for fname, label in [("group_coverage.csv", "repair experiment"),
                         ("shift_coverage.csv", "shift experiment")]:
        if not any(results_dir.rglob(fname)):
            notes.append(f"skipped {label}: no {fname} under {results_dir}")

    path = out_dir / "report.md"
    path.write_text("\n".join(lines) + "\n")
    return path, notes
